app/core/models.py
from flask import current_app

from app import db
from app.util import natural_keys

from enum import IntEnum

import datetime as dt


class Departments(db.Model):
    """ Freetext definition of the department name
    
    Departments are the highest-level objects of the system. Ultimately, all
    objects e.g. constraints and staff must be associated directly or 
    indirectly with a particular department
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200))
    
    @staticmethod
    def get_all():
        depts = Departments.query.order_by('name').all()
        return depts


    @staticmethod
    def create_new(name):
        exists = Departments.query.filter_by(name=name).first()
        if exists is not None:
            return {'status': False,
                    'message': 'Department name already exists'}
        
        dept = Departments(name=name)
        db.session.add(dept)
        db.session.commit()
        return {'status': True,
                'message': 'Success'}


class DepartmentConstraintTypes(IntEnum):
    must_have = 1
    must_not_have = 2
    nice_to_have = 3
    
    @staticmethod
    def get_all():
        constraint_list = []
        for name, number in DepartmentConstraintTypes.__members__.items():
            constraint_list.append([number.value, name.replace('_', ' ')])
        return constraint_list


class DepartmentSkillConstraints(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    department_id = db.Column(db.Integer,
                              db.ForeignKey('departments.id',
                                            ondelete='CASCADE'))
    skill_id = db.Column(db.Integer,
                         db.ForeignKey('skills.id',
                                       ondelete='CASCADE'),
                         index=True)
    level = db.Column(db.Integer)
    start_day = db.Column(db.Integer)
    start_hour = db.Column(db.Integer)
    end_day = db.Column(db.Integer)
    end_hour = db.Column(db.Integer)
    is_permanent = db.Column(db.Boolean) # Applies all week
    
    # Pseudo ForeignKey to DepartmentConstraintTypes
    constraint_type_id = db.Column(db.Integer) 
    
    @staticmethod
    def get_all():
        pass


class Staff(db.Model):
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer,
                        db.ForeignKey('users.id',
                                      ondelete='SET NULL'))
    department_id = db.Column(db.Integer,
                              db.ForeignKey('departments.id',
                                            ondelete='CASCADE'),
                              index=True)
    department = db.relationship('Departments')
    name = db.Column(db.String(50))
    skills = db.relationship('Skills', secondary='staff_skills',
                             backref=db.backref('staff', lazy='dynamic'),
                             lazy='dynamic')
    is_reserve = db.Column(db.Boolean) # Active staff or reserve
    
    @staticmethod
    def get_all(dept_id=None):
        
        staff = db.session.query(Staff)
        if dept_id is not None:
            staff = (staff.join(Departments)
                          .filter(Departments.id==int(dept_id)))
        staff = staff.all()
        staff.sort(key=lambda x: natural_keys((x.name)))
        return staff


class Skills(db.Model):
    """ Free-text name of skills that staff can possess """
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    
    @staticmethod
    def get_all():
        skills = Skills.query.all()
        skills.sort(lambda x: natural_keys(x))
        return skills


staff_skills = db.Table('staff_skills',
                        db.Column('staff_id',
                                  db.Integer,
                                  db.ForeignKey('staff.id'),
                                  primary_key=True),
                        db.Column('skill_id',
                                  db.Integer,
                                  db.ForeignKey('skills.id'),
                                  primary_key=True)
                        )


class StaffShiftConstraints(db.Model):
    
    id = db.Column(db.Integer, primary_key=True)
    staff_id = db.Column(db.Integer,
                         db.ForeignKey('staff.id',
                                       ondelete='CASCADE'),
                         index=True)
    day_number = db.Column(db.Integer)
    min_start_hour = db.Column(db.Integer)
    max_start_hour = db.Column(db.Integer)
    min_shift_hours = db.Column(db.Integer)
    max_start_hour = db.Column(db.Integer)
    min_shift_gap = db.Column(db.Integer)
    
    @staticmethod
    def get_all(staff_id):
        constraints = (StaffShiftConstraints.query
                                            .filter_by(staff_id=int(staff_id))
                                            .order_by('day_number')
                                            .all())
        return constraints
    

class WeeklyMaxHours(db.Model):
    
    id = db.Column(db.Integer, primary_key=True)
    staff_id = db.Column(db.Integer,
                         db.ForeignKey('staff.id',
                                       ondelete='CASCADE'),
                         index=True)
    hours = db.Column(db.Integer)

app/core/__init__.py
from flask import Blueprint

bp = Blueprint('core', __name__)


from app.core import routes

app/core/routes.py
from flask import request, jsonify, render_template, redirect, url_for

from app import db

from app.core import bp
from app.util import format_ajax_message

from app.auth.models import group_required
from app.core.models import Departments

from flask_login import login_required


@bp.route('/', methods=['GET'])
@login_required
def homepage():
    return render_template('core/homepage.html')


@bp.route('/get_department_list', methods=['POST'])
@login_required
def get_department_list():
    
    departments = Departments.get_all()
    department_list = []
    for dept in departments:
        dept_dict = dept.__dict__
        del dept_dict['_sa_instance_state']
        department_list.append(dept_dict)
    
    return jsonify(department_list)


@bp.route('/departments', methods=['GET'])
@login_required
def departments_home():
    departments = Departments.get_all()
    return render_template('core/departments/homepage.html',
                           departments=departments)
    
    
@bp.route('/create_department', methods=['POST'])
@login_required
def create_department():
    
    req = request.form.to_dict()
    dept_name = req.get('new_department_name')
    
    if not dept_name:
        rtn= {'status': False,
              'message': 'No department name specified',
              'template': render_template(
                              'core/departments/existing_department_table.html',
                              departments=Departments.get_all())
              }
        return jsonify(format_ajax_meassage(rtn))
    
    try:
        rtn = Departments.create_new(dept_name)
    except Exception as e:
        rtn = {'status': False,
               'message': 'Unknown exception occurred'}
    
    rtn['template'] = render_template(
                              'core/departments/existing_department_table.html',
                              departments=Departments.get_all()
                             )
    
    return jsonify(format_ajax_message(rtn))


@bp.route('/delete_department', methods=['POST'])
@login_required
def delete_department():
    
    req = request.json
    department_id = int(req.get('department_id', 0))
    print("department_id", department_id)
    department = Departments.query.get(department_id)
    if department is not None:
        db.session.delete(department)
        db.session.commit()
    
    return render_template('core/departments/existing_department_table.html',
                            departments=Departments.get_all())

app/templates/core/departments/existing_department_table.html
<table class="table table-sm table-bordered" style="width: 100%" id="existing_departments_table">
    <thead>
        <th>Name</th>
        <th></th>
        <th></th>
    </thead>
    <tbody>
        {% for department in departments %}
        <tr>
            <td><b>{{ department.name }}</b></td>
            <td><button class="btn btn-sm btn-primary" style="width: 100%">Edit</button></td>
        <td><button class="btn btn-sm btn-danger" style="width: 100%" onclick="delete_department('{{ department.id }}')">Delete</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#existing_departments_table').DataTable({
            "iDisplayLength": 10,
            "bLengthChange": false,
            "aaSorting": [],
            "searching": false,
            "info": false,
            "responsive": true,
            "columnDefs": [{
                targets: 1,
                className: 'dt-body-center'
            },
            {
                targets: 2,
                className: 'dt-body-center'
            }
            ]
        });
    });
</script>

app/templates/core/departments/homepage.html
{% extends 'core/base.html' %}
{% block content %}
{% include 'navbars/core_nav.html' %}
<div class="container-fluid content-row">
   <div class="row">
      <div class="col col-lg-6">
         <div class="card mb-3 h-100" style="border-color: #394a59">
            <div class="card-header">
               <h5>Existing Departments</h5>
            </div>
            <div class="card-body">
               <div id="existing_departments_div">{% include 'core/departments/existing_department_table.html' %}</div>
            </div>
         </div>
      </div>
      <div class="col col-lg-6">
         <div class="card mb-3 h-100" style="border-color: #394a59">
            <div class="card-header">
               <h5>Create Department</h5>
            </div>
            <div class="card-body">
               <form method="post" action="{{ url_for('core.create_department') }}" id="new_department_form"
                  autocomplete="off">
                  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                  <div class="container-fluid content-row">
                     <div class="row pb-3">
                        <div class="col col-sm-4">
                           Name
                        </div>
                        <div class="col col-sm-8">
                           <input type="text" class="form-control" style="width: 100%" name="new_department_name">
                        </div>
                     </div>
                     <div class="row">
                        <div class="col col-sm-12">
                           <input type="submit" class="btn btn-success" style="width: 100%" value="Create Department">
                        </div>
                     </div>
                  </div>
               </form>
               <div id="new_department_response_div"></div>
            </div>
         </div>
      </div>
   </div>
</div>
<script>
   $("#new_department_form").submit(function (e) {
      e.preventDefault();
      var form = $(this);
      var url = form.attr('action');

      $.ajax({
         type: "POST",
         url: url,
         data: form.serialize(),
         context: form,
         success: function (resp) {
            $("#new_department_response_div").html(resp['message']);
            $("#existing_departments_div").html(resp['template']);
         }
      });
   });
</script>
<script>
   function delete_department(department_id) {
      var csrf_token = "{{ csrf_token() }}";

      $.ajaxSetup({
         beforeSend: function (xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
               xhr.setRequestHeader("X-CSRFToken", csrf_token);
            }
         }
      });
      if (confirm("Are you sure you want to delete this department?")) {
         $.ajax({
            type: 'POST',
            data: JSON.stringify({
               'department_id': department_id,
            }),
            contentType: 'application/json; charset=utf-8',
            url: "{{ url_for('core.delete_department') }}",
            success: function (resp) {
               $("#existing_departments_div").html(resp);
            }
         });
      }
   }
</script>
{% endblock %}